name: Daily forecast and deploy

on:
  schedule:
    - cron: '15 17 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt requests

      - name: Set ENTSOE key
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        run: |
          echo "ENTSOE_API_KEY set in environment"
          test -n "$ENTSOE_API_KEY"

      - name: Daily run (predict + snapshots + sync)
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        run: |
          python scripts/daily_run.py

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

name: daily-forecast

on:
  schedule:
    - cron: "0 10 * * *"   # GitHub Actions cron je vedno v UTC - 10:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Download models
        uses: dawidd6/action-download-artifact@v3
        with:
          name: models
          path: models/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: daily-retrain.yml
          workflow_conclusion: success
        continue-on-error: true

      - name: Forecast D+1
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        run: python -m src.predict

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: forecast
          path: out/*.json
